name: Fix R2 Track List

on:
  push:
    branches: [main]

jobs:
  fix-list-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run fixListJson.ts
        run: npx tsx scripts/fixListJson.ts
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_REGION: ${{ secrets.R2_REGION }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }} 